### ISSUE TITLE
FIXES CHECKLIST

### ISSUE THREAD

**Issue by I-NOZex** [samudio12/samudio12.github.io#1]
- [x] CATEGORIAS (WEBDESIGN, UI/UX DESIGN, GRAPHIC DESIGN)
- [x] COR DA SETA SCROLL TOP
- [x] OTIMIZAR O SITE
- [x] POP-UP IMAGEM COM ZOOM (EX. AMAZON) 

O QUE ENCONTRARES QUE SE POSSA ALTERAR PODES FAZÊ-LO E DEPOIS REPORTAS-ME
